apiVersion: v1
kind: Namespace
metadata:
  name: xccxcxcxcxcxcxcxcxxc-staging
  labels:
    environment-id: env_96600dea-471b-420c-9260-1b370872c15b
    project-id: project_1175a21e-d417-442f-9900-2bc0722435ee
    project-name: xccxcxcxcxcxcxcxcxxc
    environment-name: staging
    organization-id: org_99bfadb5-996a-47d5-a5fc-442c14a28627
